name: Deploy to Cloudflare
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "stryk-insta-saver"
          directory: "frontend"
      - name: Deploy to Cloudflare Worker
        uses: cloudflare/wrangler-action@2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: publish
          workingDirectory: "worker"
